### ISSUE TITLE
GaAs Density of States file name

### ISSUE THREAD

**Issue by vvelan** [tongylin/DarkELF#1]
Hi,

This is a very small bug, but for GaAs, I think the DoS filename should be Ga_pDoS.dat and As_pDoS.dat, with a lowercase "o", not Ga_pDOS.dat and As_pDOS.dat. It seems that some versions of Python are case-sensitive when loading .dat files, whereas others are case-insensitive.

Best,
Vetri Velan

**Comment by tongylin** [comment]
Thanks for catching it! I believe it's whether the local file system is case sensitive, and we probably only tested on Mac. I've fixed it now.
